# Generated by Django 2.2.7 on 2020-02-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_info',
            name='Email_address',
            field=models.CharField(max_length=255),
        ),
    ]
