# Generated by Django 2.2.7 on 2020-02-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_info', '0002_auto_20200207_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_info',
            name='Email_address',
        ),
    ]
