# Generated by Django 2.2.7 on 2020-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_info', '0004_request_info_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_info',
            name='Question',
            field=models.TextField(max_length=1000),
        ),
    ]
