# Generated by Django 2.2.7 on 2020-02-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_info', '0005_auto_20200209_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_info',
            name='Question',
            field=models.CharField(max_length=1000),
        ),
    ]
