# Generated by Django 2.2.7 on 2020-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='D_O_B',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
