# Generated by Django 2.2.7 on 2020-01-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountant',
            field=models.BooleanField(default=False),
        ),
    ]
