# Generated by Django 2.2.7 on 2020-02-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('main_content', models.CharField(max_length=255)),
            ],
        ),
    ]
