# Generated by Django 2.2.7 on 2020-02-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.TextField(max_length=255),
        ),
    ]
