# Generated by Django 2.2.7 on 2020-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20200206_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(max_length=255),
        ),
    ]
