# Generated by Django 2.2.7 on 2020-02-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200206_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('new_content', models.CharField(max_length=500)),
            ],
        ),
    ]
