# Generated by Django 2.2.7 on 2020-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_latest_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_news',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
