# Generated by Django 2.2.7 on 2020-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpayment',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
