# Generated by Django 2.2.7 on 2020-01-25 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_finalpayment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpayment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
