# Generated by Django 2.2.7 on 2020-01-25 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_finalpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalpayment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
