# Generated by Django 2.2.7 on 2020-01-25 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200125_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalpayment',
            name='date',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
        ),
    ]
