# Generated by Django 2.2.7 on 2020-01-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200125_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpayment',
            name='paymentamount',
            field=models.CharField(default='60000', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalpayment',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
