# Generated by Django 2.2.7 on 2020-01-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymentinfo_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpayment',
            name='section',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
