# Generated by Django 2.2.7 on 2020-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_finalpayment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalpayment',
            name='paymentamount',
            field=models.IntegerField(),
        ),
    ]
