# Generated by Django 2.2.7 on 2020-01-07 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_of_student',
            fields=[
                ('class_of_student', models.CharField(default='this', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('year_of_admission', models.CharField(max_length=23)),
                ('D_O_B', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=255)),
                ('local_government_area', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('Religion', models.CharField(max_length=255)),
                ('admission_number', models.CharField(default='1506', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_name',
            fields=[
                ('Subject_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term', models.CharField(default='emptyoo', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.CharField(default='is', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.CharField(max_length=255)),
                ('second_test', models.CharField(max_length=255)),
                ('exam_score', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_Datasss.Class_of_student')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_Datasss.Subject_name')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_Datasss.Term')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_Datasss.Year')),
            ],
        ),
    ]
