# Generated by Django 2.2.7 on 2020-01-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_Datasss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_result',
            old_name='studentclass',
            new_name='class_of_student',
        ),
    ]
