# Generated by Django 2.2.7 on 2020-01-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_Datasss', '0002_auto_20200107_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_result',
            old_name='class_of_student',
            new_name='studentclass',
        ),
    ]
