# Generated by Django 2.2.7 on 2020-01-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_Datasss', '0003_auto_20200107_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_result',
            name='exam_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_result',
            name='first_test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_result',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_result',
            name='second_test',
            field=models.IntegerField(),
        ),
    ]
