# Generated by Django 2.2.7 on 2020-01-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_Datasss', '0005_auto_20200108_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_result',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
