# Generated by Django 2.2.7 on 2020-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_Datasss', '0007_student_result_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_result',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
