# Generated by Django 2.2.7 on 2020-01-08 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_Datasss', '0008_auto_20200108_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='registered_username',
            field=models.OneToOneField(default='student@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
