# Generated by Django 2.2.7 on 2020-01-08 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_Datasss', '0009_student_data_registered_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='registered_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
